# Generated by Django 2.0.4 on 2018-04-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_id', models.CharField(max_length=15, verbose_name='Reddit Id')),
                ('title', models.CharField(default='N/A', max_length=300, verbose_name='Title')),
                ('author', models.CharField(default='N/A', max_length=60, verbose_name='Author')),
                ('ups', models.IntegerField(default=0, verbose_name='Ups')),
                ('num_comments', models.IntegerField(default=0, verbose_name='Number of Comments')),
                ('created_at', models.CharField(default='N/A', max_length=15, verbose_name='Created at')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ('created_at',),
            },
        ),
    ]
