# Generated by Django 2.0.4 on 2018-04-13 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20180412_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_at', '-ups'), 'verbose_name_plural': 'Posts'},
        ),
    ]
