# Generated by Django 2.0.4 on 2018-04-13 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20180413_0248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'Posts'},
        ),
    ]
